import random

# The original text
text = """A Journey Through a Small Town Nestled between rolling hills and lush forests, there lies a small town 
named Maplewood. This town, with its charm and simplicity, is a place where life moves at a gentle pace. Its streets 
are lined with old trees and cozy houses, each telling a story of its own. The air is filled with the sweet scent of 
blooming flowers, and the sounds of chirping birds create a soothing melody. At the heart of Maplewood is the town 
square. It is a bustling hub of activity, especially on market days. On these days, vendors set up colorful stalls, 
selling fresh produce, homemade bread, and various handmade crafts. The market is a favorite spot for locals to 
gather, chat with friends, and enjoy the lively atmosphere. The smell of freshly baked goods wafts through the air, 
mingling with the aroma of ripe fruits and vegetables. Maplewood has a strong sense of community. People know their 
neighbors and often stop to exchange greetings. The town's residents are friendly and welcoming, always ready to lend 
a helping hand. This close-knit community spirit is evident in the numerous local events held throughout the year. 
From summer fairs to winter festivals, there is always something happening in Maplewood. One of the most beloved 
traditions is the annual Maplewood Harvest Festival. This event, held every fall, celebrates the town's agricultural 
roots. The festival features a range of activities, including a pumpkin carving contest, a pie-eating competition, 
and a lively parade. The highlight of the festival is the corn maze, a favorite among children and adults alike. The 
maze is designed to challenge visitors while offering a fun and memorable experience. The town’s school is an 
integral part of the community. It is a small, yet vibrant place where children learn and grow. The teachers are 
dedicated and passionate, always striving to create a nurturing environment. The school hosts various events, 
such as science fairs and talent shows, which bring the whole town together. Parents and students alike take pride in 
these events, which showcase the talents and achievements of the young learners. Maplewood is also home to a number 
of local businesses that add to its charm.apple, orange, banana, table, chair, house, car, tree, dog, cat, bird, 
fish, book, pen, paper, shirt, shoe, hat, ball, cup, plate, spoon, fork, knife, window, door, bed, sofa, rug, lamp, 
television, radio, phone, clock, calendar, picture, box, bag, key, wallet, pencil, eraser, notebook, desk, shelf, 
drawer, suitcase, jacket, sweater, coat, pants, dress, shorts, socks, gloves, umbrella, hat, boot, belt, tie, scarf, 
hat, glasses, toothbrush, toothpaste, soap, shampoo, towel, comb, brush, mirror, stove, oven, fridge, microwave, 
sink, table, chair, sofa, bed, dresser, closet, basket, bin, blanket, pillow, mattress, rug, curtain, curtain, door, 
lock, handle, bell, doorknob, keyhole, garage, attic, basement, stairs, ladder, balcony, fence, gate, garden, park, 
playground, street, road, sidewalk, car, bike, bus, train, airplane, boat, ferry, taxi, truck, tractor, motorcycle, 
scooter, moped, wheelbarrow, sled, skates, helmet, padlock, chain, rope, nail, screw, hammer, wrench, screwdriver, 
pliers, saw, drill, tape, glue, paint, brush, canvas, easel, sculpture, statue, fountain, pond, stream, river, lake, 
ocean, sea, beach, mountain, hill, valley, desert, forest, jungle, meadow, field, grove, orchard, vineyard, farm, 
barn, silo, windmill, barn, greenhouse, shed, stable, coop, kennel, pen, cage, leash, collar, harness, saddle, 
bridle, hoof, fur, feathers, beak, claws, paws, tail, whiskers, scales, shell, fin, gills, antlers, horns, tusks, 
mane, snout, trunk, tusks, beak, bill, claws, wings, flippers, paws, hooves, fins, spines, feathers, shell, skin, 
hair, feathers, fur, scales, shells, silk, velvet, leather, cotton, wool, denim, polyester, nylon, satin, silk, 
linen, corduroy, velvet, fleece, felt, canvas, canvas, tweed, lace, mesh, fur, fringe, bead, sequins, glitter, paint, 
dye, ink, charcoal, pastels, crayons, markers, pen, pencil, chalk, eraser, sharpener, ruler, protractor, compass, 
set, binder, folder, envelope, stamp, postcard, letter, card, note, memo, book, magazine, newspaper, novel, 
dictionary, thesaurus, atlas, guide, brochure, pamphlet, flyer, menu, recipe, cookbook, journal, diary, planner, 
agenda, calendar, schedule, timetable, clock, watch, alarm, bell, buzzer, timer, gauge, meter, scale, balance, ruler, 
caliper, micrometer, thermometer, barometer, compass, sextant, GPS, map, chart, graph, diagram, illustration, 
drawing, painting, sculpture, photograph, picture, portrait, landscape, still-life, abstract, collage, mosaic, 
fresco, mural, tapestry, quilt, rug, mat, blanket, pillow, cushion, curtain, drape, screen, shade, blind, awning, 
canopy, umbrella, parasol, tent, shelter, hut, cabin, cottage, house, apartment, condo, villa, mansion, palace, 
castle, fortress, wall, fence, gate, door, window, roof, chimney, attic, cellar, basement, garage, driveway, path, 
sidewalk, porch, deck, patio, garden, yard, lawn, hedge, bush, shrub, tree, flower, plant, herb, vegetable, fruit, 
root, leaf, stem, petal, bud, blossom, bloom, seed, bulb, tuber, vine, branch, twig, trunk, bark, canopy, canopy, 
canopy, forest, woodland, grove, glade, clearing, meadow, field, pasture, range, farmland, ranch, homestead, estate, 
plot, lot, parcel, section, zone, district, neighborhood, community, village, town, city, metropolis, capital, 
county, province, state, country, continent, planet, universe, galaxy, star, moon, sun, comet, asteroid, meteor, 
nebula, black hole, white dwarf, supernova, quasar, pulsar, galaxy, cluster, cosmos, space, void, vacuum, orbit, 
axis, rotation, revolution, phase, cycle, tide, current, wave, ripple, surge, swell, stream, flow, drip, drop, mist, 
fog, haze, cloud, rain, snow, sleet, hail, thunder, lightning, storm, gale, breeze, wind, draft, air, atmosphere, 
climate, weather, season, temperature, humidity, pressure, barometer, thermometer, forecast, report, warning, alert, 
notification, signal, message, transmission, communication, broadcast, telecast, transmission, reception, frequency, 
wavelength, amplitude, signal, wave, pulse, data, information, record, file, document, text, message, code, program, 
software, hardware, system, device, machine, tool, equipment, apparatus, instrument, gadget, contraption, mechanism, 
engine, motor, pump, fan, heater, cooler, air conditioner, refrigerator, washer, dryer, oven, stove, microwave, 
toaster, blender, mixer, coffee maker, kettle, grill, fryer, toaster, oven, skillet, pot, pan, bowl, dish, cup, 
glass, mug, plate, fork, knife, spoon, chopsticks, napkin, tablecloth, placemat, tray, basket, bucket, container, 
jar, bottle, can, tin, packet, bag, sack, box, crate, carton, package, parcel, envelope, pouch, case, cover, lid, 
cap, stopper, plug, seal, gasket, o-ring, tape, glue, adhesive, paste, solvent, cleaner, detergent, soap, shampoo, 
conditioner, lotion, cream, ointment, balm, medicine, drug, pill, tablet, capsule, injection, vaccine, bandage, 
plaster, dressing, gauze, cotton, swab, wipe, towel, sponge, brush, comb, razor, scissors, tweezers, clippers, file, 
emery board, nail polish, remover, perfume, cologne, deodorant, aftershave, makeup, foundation, powder, blush, 
lipstick, eyeliner, mascara, eye shadow, nail polish, remover, lotion, soap, shampoo, conditioner, bath gel, 
bath salts, scrub, cream, balm, oil, gel, mousse, spray, mist, aerosol, powder, base, gloss, tint, tint, tint, shade, 
hue, color, tone, gradient, shade, tint, swatch, palette, canvas, easel, brush, paint, watercolor, acrylic, oil, 
pastel, charcoal, pencil, crayon, marker, pen, ink, dye, stain, varnish, sealant, finish, coat, layer, texture, 
pattern, design, motif, style, trend, fashion, model, brand, label, logo, trademark, icon, symbol, emblem, badge, 
insignia, sign, banner, poster, flyer, pamphlet, brochure, leaflet, booklet, catalog, magazine, newspaper, journal, 
diary, notebook, planner, agenda, calendar, schedule, timetable, record, log, journal, diary, book, novel, story, 
tale, legend, myth, fable, parable, poem, verse, rhyme, lyric, song, chant, jingle, anthem, hymn, melody, tune, 
chord, note, scale, harmony, rhythm, beat, tempo, meter, measure, phrase, passage, section, movement, composition, 
opus, work, piece, track, recording, performance, concert, recital, show, play, drama, opera, ballet, musical, 
comedy, act, scene, character, actor, actress, director, producer, playwright, screenwriter, script, dialogue, 
monologue, soliloquy, aside, cue, rehearsal, audition, casting, crew, production, set, stage, costume, prop, makeup, 
lighting, sound, music, score, soundtrack, audio, video, film, movie, cinema, theater, studio, gallery, museum, 
exhibit, installation, sculpture, painting, drawing, print, photograph, artwork, creation, masterpiece, artifact, 
relic, antique, treasure, gem, jewel, diamond, pearl, ruby, sapphire, emerald, topaz, amethyst, opal, jade, 
turquoise, coral, shell, ivory, bone, wood, metal, silver, gold, platinum, bronze, copper, iron, steel, alloy, 
carbon, glass, crystal, plastic, rubber, foam, fabric, textile, thread, yarn, wool, silk, cotton, linen, polyester, 
nylon, rayon, acetate, spandex, elastane, leather, suede, felt, fleece, denim, corduroy, tweed, flannel, velvet, 
satin, silk, lace, mesh, chiffon, organza, tulle, net, canvas, burlap, jute, hemp, sisal, straw, reed, bamboo, 
rattan, wicker, cane, wood, plywood, chipboard, particle board, fiberboard, MDF, OSB, cement, plaster, concrete, 
brick, stone, tile, slate, granite, marble, quartz, sandstone, limestone, clay, earth, soil, sand, gravel, rock, 
mineral, gem, crystal, fossil, shell, coral, pearl, seed, bulb, sprout, shoot, plant, flower, leaf, stem, root, 
branch, trunk, bark, canopy, forest, grove, glade, meadow, field, pasture, range, farm, ranch, homestead, estate, 
plot, lot, parcel, section, zone, district, neighborhood, community, village, town, city, metropolis, capital, 
county, province, state, country, continent, planet, universe, galaxy, star, moon, sun, comet, asteroid, meteor, 
nebula, black hole, white dwarf, supernova, quasar, pulsar, galaxy, cluster, cosmos, space, void, vacuum, orbit, 
axis, rotation, revolution, phase, cycle, tide, current, wave, ripple, surge, swell, stream, flow, drip, drop, mist, 
fog, haze, cloud, rain, snow, sleet, hail, thunder, lightning, storm, gale, breeze, wind, draft, air, atmosphere, 
climate, weather, season, temperature, humidity, pressure, barometer, thermometer, forecast, report, warning, alert, 
notification, signal, message, transmission, communication, broadcast, telecast, transmission, reception, frequency, 
wavelength, amplitude, signal, wave, pulse, data, information, record, file, document, text, message, code, program, 
software, hardware, system, device, machine, tool, equipment, apparatus, instrument, gadget, contraption, mechanism, 
engine, motor, pump, fan, heater, cooler, air conditioner, refrigerator, washer, dryer, oven, stove, microwave, 
toaster, blender, mixer, coffee maker, kettle, grill, fryer, toaster, oven, skillet, pot, pan, bowl, dish, cup, 
glass, mug, plate, fork, knife, spoon, chopsticks, napkin, tablecloth, placemat, tray, basket, bucket, container, 
jar, bottle, can, tin, packet, bag, sack, box, crate, carton, package, parcel, envelope, pouch, case, cover, lid, 
cap, stopper, plug, seal, gasket, o-ring, tape, glue, adhesive, paste, solvent, cleaner, detergent, soap, shampoo, 
conditioner, bath gel, bath salts, scrub, cream, balm, oil, gel, mousse, spray, mist, aerosol, powder, base, gloss, 
tint, shade, hue, color, tone, gradient, shade, tint, swatch, palette, canvas, easel, brush, paint, watercolor, 
acrylic, oil, pastel, charcoal, pencil, crayon, marker, pen, ink, dye, stain, varnish, sealant, finish, coat, layer, 
texture, pattern, design, motif, style, trend, fashion, model, brand, label, logo, trademark, icon, symbol, emblem, 
badge, insignia, sign, banner, poster, flyer, pamphlet, brochure, leaflet, booklet, catalog, magazine, newspaper, 
journal, diary, notebook, planner, agenda, calendar, schedule, timetable, record, log, journal, diary, book, novel, 
story, tale, legend, myth, fable, parable, poem, verse, rhyme, lyric, song, chant, jingle, anthem, hymn, melody, 
tune, chord, note, scale, harmony, rhythm, beat, tempo, meter, measure, phrase, passage, section, movement, 
composition, opus, work, piece, track, recording, performance, concert, recital, show, play, drama, opera, ballet, 
musical, comedy, act, scene, character, actor, actress, director, producer, playwright, screenwriter, script, 
dialogue, monologue, soliloquy, aside, cue, rehearsal, audition, casting, crew, production, set, stage, costume, 
prop, makeup, lighting, sound, music, score, soundtrack, audio, video, film, movie, cinema, theater, studio, gallery, 
museum, exhibit, installation, sculpture, painting, drawing, print, photograph, picture, portrait, landscape, 
still-life, abstract, collage, mosaic, fresco, mural, tapestry, quilt, rug, mat, blanket, pillow, cushion, curtain, 
drape, screen, shade, blind, awning, canopy, umbrella, parasol, tent, shelter, hut, cabin, cottage, house, apartment, 
condo, villa, mansion, palace, castle, fortress, wall, fence, gate, door, window, roof, chimney, attic, cellar, 
basement, garage, driveway, path, sidewalk, porch, deck, patio, garden, yard, lawn, hedge, bush, shrub, tree, flower, 
plant, herb, vegetable, fruit, root, leaf, stem, petal, bud, blossom, bloom, seed, bulb, tuber, vine, branch, twig, 
trunk, bark, canopy, forest, woodland, grove, glade, clearing, meadow, field, pasture, range, farmland, ranch, 
homestead, estate, plot, lot, parcel, section, zone, district, neighborhood, community, village, town, city, 
metropolis, capital, county, province, state, country, continent, planet, universe, galaxy, star, moon, sun, comet, 
asteroid, meteor, nebula, black hole, white dwarf, supernova, quasar, pulsar, galaxy, cluster, cosmos, space, void, 
vacuum, orbit, axis, rotation, revolution, phase, cycle, tide, current, wave, ripple, surge, swell, stream, flow, 
drip, drop, mist, fog, haze, cloud, rain, snow, sleet, hail, thunder, lightning, storm, gale, breeze, wind, draft, 
air, atmosphere, climate, weather, season, temperature, humidity, pressure, barometer, thermometer, forecast, report, 
warning, alert, notification, signal, message, transmission, communication, broadcast, telecast, transmission, 
reception, frequency, wavelength, amplitude, signal, wave, pulse, data, information, record, file, document, text, 
message, code, program, software, hardware, system, device, machine, tool, equipment, apparatus, instrument, gadget, 
contraption, mechanism, engine, motor, pump, fan, heater, cooler, air conditioner, refrigerator, washer, dryer, oven, 
stove, microwave, toaster, blender, mixer, coffee maker, kettle, grill, fryer, toaster, oven, skillet, pot, pan, 
bowl, dish, cup, glass, mug, plate, fork, knife, spoon, chopsticks, napkin, tablecloth, placemat, tray, basket, 
bucket, container, jar, bottle, can, tin, packet, bag, sack, box, crate, carton, package, parcel, envelope, pouch, 
case, cover, lid, cap, stopper, plug, seal, gasket, o-ring, tape, glue, adhesive, paste, solvent, cleaner, detergent, 
soap, shampoo, conditioner, bath gel, bath salts, scrub, cream, balm, oil, gel, mousse, spray, mist, aerosol, powder, 
base, gloss, tint, shade, hue, color, tone, gradient, shade, tint, swatch, palette, canvas, easel, brush, paint, 
watercolor, acrylic, oil, pastel, charcoal, pencil, crayon, marker, pen, ink, dye, stain, varnish, sealant, finish, 
coat, layer, texture, pattern, design, motif, style, trend, fashion, model, brand, label, logo, trademark, icon, 
symbol, emblem, badge, insignia, sign, banner, poster, flyer, pamphlet, brochure, leaflet, booklet, catalog, 
magazine, newspaper, journal, diary, notebook, planner, agenda, calendar, schedule, timetable, record, log, journal, 
diary, book, novel, story, tale, legend, myth, fable, parable, poem, verse, rhyme, lyric, song, chant, jingle, 
anthem, hymn, melody, tune, chord, note, scale, harmony, rhythm, beat, tempo, meter, measure, phrase, passage, 
section, movement, composition, opus, work, piece, track, recording, performance, concert, recital, show, play, 
drama, opera, ballet, musical, comedy, act, scene, character, actor, actress, director, producer, playwright, 
screenwriter, script, dialogue, monologue, soliloquy, aside, cue, rehearsal, audition, casting, crew, production, 
set, stage, costume, prop, makeup, lighting, sound, music, score, soundtrack, audio, video, film, movie, cinema, 
theater, studio, gallery, museum, exhibit, installation, sculpture, painting, drawing, print, photograph, picture, 
portrait, landscape, still-life, abstract, collage,"""


def get_words(num):
    words = text.replace(',', '').replace('.', '')
    words_list = words.split()
    random.shuffle(words_list)
    return words_list[:num]
